#!/usr/bin/python3

# Extract "slow" data for resistor calibrations.
# data1/R<n>.dat -> data1/R<n>_slow.dat
# - skip all points measured in single-channel mode (measured faster then 10s)
# - use columns 0 (time), 1 (resistance), 3 (power)
# - skip data according with the skiplist (data_slow_skiplist file)
import numpy

skiplist = numpy.loadtxt("data_slow_skiplist", unpack=True, usecols=(0,1,2));
t0 = 1609862308.174

for n in (1,2,3,4,5,6):
  # load data
  data = numpy.loadtxt("data1/R%d.dat"%(n), comments='#', unpack=True, usecols=(0,1,3));
  s = len(data[0])

  fo = open("data1/R%d_slow.dat"%(n), "w")
  print( "#time resistance power", file=fo)

  for i in range(0,s):
    if (i>0   and data[0][i]-data[0][i-1] < 10): continue;
    if (i<s-1 and data[0][i+1]-data[0][i] < 10): continue;

    sk=0;
    for j in range(0, len(skiplist[0])):
      if skiplist[0][j] == n and\
         skiplist[1][j]+t0 < data[0][i] and\
         skiplist[2][j]+t0 >= data[0][i]:
        sk=1
        break
    if sk: continue

    print( "%f %e %e" % (data[0][i], data[1][i], data[2][i]), file=fo)
